"""empty message

Revision ID: 178e1517fb0d
Revises: 62b92b7d9aef
Create Date: 2019-12-19 11:44:23.081275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '178e1517fb0d'
down_revision = '62b92b7d9aef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('idx', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('course_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_user',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], name='course_user_course_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='course_user_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'course_id', name='course_user_pkey')
    )
    op.drop_table('learning')
    # ### end Alembic commands ###
