"""empty message

Revision ID: 30e3c8b569e5
Revises: 178e1517fb0d
Create Date: 2019-12-22 16:24:34.823410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30e3c8b569e5'
down_revision = '178e1517fb0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('thumbnail', sa.String(length=500), nullable=True))
    op.add_column('video', sa.Column('url', sa.String(length=500), nullable=True))
    op.drop_column('video', 'cover')
    op.drop_column('video', 'video_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('video_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('video', sa.Column('cover', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('video', 'url')
    op.drop_column('video', 'thumbnail')
    # ### end Alembic commands ###
