"""empty message

Revision ID: da60c02a675f
Revises: 
Create Date: 2020-01-01 10:54:32.350769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da60c02a675f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('learning', sa.Column('progress', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('learning', 'progress')
    # ### end Alembic commands ###
